배틀 기록을 담는 도큐먼트를 생성한다.
SWM-KAWAI-MANS/party-run-battle-service pull request #11
Opened 2023-07-20 09:23 UTC by seong-wooo

## 변경 사항
배틀에 속한 러너가 모두 RUNNING 상태로 변경되면, 배틀에 속하는 러너들의 기록을 저장하는 RunnerRecord를 생성해보았습니다.
이 RunnerRecord 도큐먼트를 미리 생성하지 않으면, 발생하는 문제는 아래와 같습니다.

### 러너가 **좌표**와 **시간**을 통해 현재까지의 이동 거리를 요청할 때

RunnerRecord 도큐먼트가 존재하는지 확인하는 로직을 거쳐야합니다.
즉, 배틀 과정에서 매 요청마다 로직 하나를 더 거쳐야합니다.

 
## 알아야할 사항
이전에 배틀에 속한 러너가 모두 RUNNING 상태로 변경되면, 스프링 이벤트를 통해 러너들에게 배틀 시작 시간을 넘겨주는 로직을 구현하였습니다.
마찬가지로, 같은 스프링 이벤트를 통해 같은 시점에 현재 생성한 로직을 실행합니다.

## 테스트 방식
러너들이_구독_성공_요청을_보냈을_때 모두_보냈다면 배틀 시작 시간을 응답한다. 테스트에서 eventHandler가 잘 실행되는 것을 확인하였습니다. ( 디버깅으로 )

2023-07-20 11:00 UTC, phjppo0918 requested changes
수정한 이후에 머지 진행하시져

2023-07-20 11:00 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/record/repository/RunnerRecordDao.java
> +                .collect(Collectors.toList());
예

2023-07-20 11:01 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/record/controller/RecordEventHandler.java
> +@Controller
`뭔가` 라는 확신 없는 리뷰가 별로네요!
저도 Component가 더 적합하다고 느낍니다.

2023-07-21 08:34 UTC, phjppo0918 approved these changes
LGTM

2023-07-21 08:34 UTC, merged