배틀 진행 시, GPS 좌표에 속력 제한 기능을 추가한다.
SWM-KAWAI-MANS/party-run-battle-service pull request #39
Opened 2023-08-23 06:22 UTC by seong-wooo

## 변경 사항
기존에는 GPS 좌표가 튀는 현상을 막지 못하였습니다.

속력 제한은 GPS 좌표 보정 과정 중, 첫 번째 작업입니다.
GPS 좌표를 통해 새로운 기록을 만들 때, 속력 제한 기능을 두어 제한 속력을 넘어가면 해당 GPS 좌표를 무시하도록 했습니다. 

Runner, RunnerRecord, GpsData 3개를 집중적으로 보면 좋을 것 같아요.
로직이 조금 더러워서 로직적으로도 신경써서 봐주세요.

## 알아야할 사항
속력 제한을 넣기 전의 테스트들은 모두 속력 제한이 없었기 때문에, 데이터 값을 모두 변경했어야했습니다.
따라서 file change가 많다고 생각이 될 것입니다.
하지만 이를 분리할 수는 없습니다.

## 테스트 방식
기존의 방식과 속력 제한 기능이 추가된 방식을 비교해야합니다.
안드로이드에서 직접 확인해야합니다.
이전 버전을 먼저 테스트하고 이 PR을 머지할 예정입니다.

2023-08-23 07:03 UTC, phjppo0918 requested changes
비즈니스 로직이 많이 어렵네요. 구현하면서 고민 많으셨을 것 같은데 고생 많으셨습니다. 해당 부분만 픽스해서 머지 진행하시죠!

2023-08-23 07:03 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
> +
```suggestion
    private List<RunnerRecord> createRecords(RunnerRecord record, List<GpsData> gpsData) {
        return gpsData.stream()
                .map(record::createNextRecord)
                .filter(Optional::isPresent)
                .map(Optional::get)
                .toList();
    }
```

2023-08-23 07:03 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
> +
어떤가요?

2023-08-23 07:05 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
> +    private static final int FIRST_GPSDATA_INDEX = 0;
네 변경했습니다.

2023-08-23 07:05 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
추가적으로 field에 단위까지 표현하는거는 약간의 TMI일 수도 있다 생각합니다!!

2023-08-23 07:14 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
```java

final double runnerSpeed = movingDistance / this.gpsData.calculateDuration(gpsData);
        if (movingDistance == MIN_DURATION_SECOND || runnerSpeed < MAXIMUM_RUNNER_SPEED_OF_METERS_PER_SECOND) {
            return Optional.empty();
        }
```
이렇게하면 runnerSpeed를 구할 때 분모에 `0`이 들어갈 수도 있습니다. 자바에서는 분모가 0인 경우에 `ArithmeticException`이 발생하는 것으로 알고 있습니다.
하지만 테스트에서 체크해보았을 때는 분모가 0인 값으로 나누었을 때 runnerSpeed가 `nan`으로 들어가는 것을 보았습니다. 예외는 발생하지 않더라구요.
예외는 발생하지 않았지만, 분모가 0인 상황을 막는 것이 더 중요하다고 생각합니다.

다만 제시한 변수명처럼 변수명은 변경하겠습니다.

2023-08-23 07:18 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
이전 코드도 분모가 0인 상황을 막지 않는 것 같은데요! 어차피 분모에 대한 validation은 필요해보입니다!

2023-08-23 07:24 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
추가로 현재 거리가 0인  것에 대해서 검증을 하고 있는데
시간이 0인 것에 대하여 검증하는 로직으로 변경했습니다.

2023-08-23 07:25 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
> +
안됩니다. 
제가 지금 테스트에서 거리를 확인하지 않아서, 이렇게 바꾸어도 테스트가 모두 통과하는데요.

예시를 들어보면 
```
record : (0,0)
List<gpsData> : [(1,1), (2,2), (3,3)]
```

위처럼 좌표가 존재한다고 할 때,
위의 반복문은 
(0,0) 과 (1,1)를 비교하여 새로운 좌표 생성
(0,0) 과 (2,2)를 비교하여 새로운 좌표 생성
(0,0) 과 (3,3)를 비교하여 새로운 좌표 생성

이렇게 되면 거리가 잘못 측정 되겠죠..?

기존의 반복문은
(0,0) 과 (1,1)를 비교하여 새로운 좌표 생성
(1,1) 과 (2,2)를 비교하여 새로운 좌표 생성
(2,2) 과 (3,3)를 비교하여 새로운 좌표 생성

로 진행됩니다.

2023-08-23 07:27 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
> 추가적으로 field에 단위까지 표현하는거는 약간의 TMI일 수도 있다 생각합니다!!

단위는 중요하다고 생각합니다.
m/s 인지 km/s 인지에 따라서 서비스 자체가 달라집니다.

2023-08-23 07:59 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/Runner.java
> +
변경해도 테스트 성공하길래 바꿔도 되는지 알았네용 확인했습니다!

2023-08-23 08:08 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        }
변경했어요~

2023-08-27 23:39 UTC, phjppo0918 requested changes

2023-08-27 23:39 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        return Optional.empty();
```java
 if (durationSeconds == MIN_DURATION_SECOND || MAXIMUM_RUNNER_SPEED_OF_METERS_PER_SECOND < movingDistanceMeter / durationSeconds) {
             return Optional.empty();
         }
             return Optional.of(new RunnerRecord(gpsData, this.distance + movingDistanceMeter));
         
```
이런 식은 어떨까요?

2023-08-28 08:04 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/entity/record/RunnerRecord.java
> +        return Optional.empty();
수정했습니다!

2023-08-28 08:11 UTC, merged