로깅을 구체화한다.
SWM-KAWAI-MANS/party-run-battle-service pull request #45
Opened 2023-09-03 00:24 UTC by seong-wooo

## 변경 사항

## 알아야할 사항

## 테스트 방식

2023-09-03 00:42 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/battle/dto/BattleResponse.java
> +import java.awt.*;
뭐죠?

2023-09-03 00:46 UTC, phjppo0918 requested changes
로그를 명확하게 찍는 것은 좋게 생각합니다. 허나, 메인 로직에 로그 로직이 섞이는 것이 과연 좋다고 하기는 힘들 것 같은데, 기존 AOP를 통한 로깅을 좀 더 구체적으로 타게팅해서 진행하는 방식이 아닌, 필터를 적용한 로깅을 도입한 이유가 있나요?

2023-09-04 02:48 UTC, phjppo0918 approved these changes
고생하셨습니다. 코멘트 확인하시고 문제 없으면 머지 진행하세요

2023-09-04 02:48 UTC, phjppo0918 commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerResponse.java
> +        return String.format("RunnerResponse{id: %s, rank: %d, endTime: %s)", id, rank, endTime);
열리는건 중괄호, 닫는건 소괄호인데 의도한건가요?

2023-09-04 04:25 UTC, seong-wooo commented on src/main/java/online/partyrun/partyrunbattleservice/domain/runner/dto/RunnerResponse.java
> +        return String.format("RunnerResponse{id: %s, rank: %d, endTime: %s)", id, rank, endTime);
수정했습니다.

2023-09-04 04:29 UTC, merged